version: 2

models:
  - name: stg_dbt_core
    description: "Staged stargazers for dbt-labs/dbt-core."
    columns: &stargazer_columns
      - name: user_login
        tests: [not_null]
      - name: user_id
        tests: [not_null]
      - name: repo
        tests: [not_null]
      - name: starred_at
        tests: [not_null]

  - name: stg_airflow
    description: "Staged stargazers for apache/airflow."
    columns: *stargazer_columns

  - name: stg_dagster
    description: "Staged stargazers for dagster-io/dagster."
    columns: *stargazer_columns

  - name: stg_duckdb
    description: "Staged stargazers for duckdb/duckdb."
    columns: *stargazer_columns

  - name: stg_dlt
    description: "Staged stargazers for dlt-hub/dlt."
    columns: *stargazer_columns
