version: 2

models:
  - name: stg_stargazers
    description: "Cleaned, typed stargazer records. One row per (user, repo) star event."
    columns:
      - name: user_login
        description: "GitHub username."
        tests:
          - not_null
      - name: user_id
        description: "Numeric GitHub user ID."
        tests:
          - not_null
      - name: repo
        description: "Repository in owner/repo format."
        tests:
          - not_null
          - accepted_values:
              values:
                - "dbt-labs/dbt-core"
                - "apache/airflow"
                - "dagster-io/dagster"
                - "duckdb/duckdb"
                - "dlt-hub/dlt"
      - name: starred_at
        description: "Timestamp of the star event."
        tests:
          - not_null
