version: 2

sources:
  - name: raw
    schema: main
    description: "Raw stargazer records loaded from the GitHub API — one table per repo."
    tables:
      - name: raw_dbt_core
        description: "Stargazers for dbt-labs/dbt-core."
      - name: raw_airflow
        description: "Stargazers for apache/airflow."
      - name: raw_dagster
        description: "Stargazers for dagster-io/dagster."
      - name: raw_duckdb
        description: "Stargazers for duckdb/duckdb."
      - name: raw_dlt
        description: "Stargazers for dlt-hub/dlt."
