version: 2

models:
  - name: dim_stargazers
    description: "All stargazer events — a materialized pass-through of int_stargazers."
    columns:
      - name: user_login
        tests: [not_null]
      - name: user_id
        tests: [not_null]
      - name: repo
        tests: [not_null]
      - name: starred_at
        tests: [not_null]
