version: 2

models:
  - name: stargazer_summary
    description: >
      One row per GitHub user. Summarises their engagement with our tracked
      repos: total repos starred, which repos, and when they first and last
      starred one.
    columns:
      - name: user_id
        description: "Stable numeric GitHub user ID (primary key)."
        tests:
          - not_null
          - unique
      - name: user_login
        description: "GitHub username (may change; user_id is the stable key)."
        tests:
          - not_null
      - name: repos_starred_count
        description: "Number of tracked repos this user has starred."
        tests:
          - not_null
      - name: repos_starred
        description: "Ordered list of repos starred, from earliest to latest."
      - name: first_starred_at
        description: "Timestamp of this user's earliest star across all tracked repos."
      - name: last_starred_at
        description: "Timestamp of this user's most recent star across all tracked repos."

  - name: mart_stars_per_repo
    description: "Total star count per tracked repo."
    columns:
      - name: repo
        tests: [not_null, unique]
      - name: total_stars
        tests: [not_null]

  - name: mart_stars_over_time
    description: "Daily and cumulative star counts per repo over time."
    columns:
      - name: repo
        tests: [not_null]
      - name: starred_date
        tests: [not_null]
      - name: stars_on_day
        tests: [not_null]
      - name: cumulative_stars
        tests: [not_null]

  - name: mart_stargazer_overlap
    description: "Number of users grouped by how many tracked repos they have starred."
    columns:
      - name: repos_starred_count
        tests: [not_null, unique]
      - name: user_count
        tests: [not_null]
